#!/bin/bash
#
NTSTEPS=1000
TAU=0.01
#
for ((i = 0 ; i < $NTSTEPS ; i++ )); do echo "$TAU*$i" | bc -l; done | \
    parallel --joblog=gpar.log -k './render {}' | \
    ffmpeg -f image2 -r 10.0 -y -f png_pipe -i pipe: -pix_fmt yuv420p -qscale 1 movie.mp4