#!/bin/bash
#
help() {
    echo "Usage: render [OPTION...]"
    echo
    echo "  -h, --help                 display this usage synopsis"
    echo "  -v, --verbose              enable debug output"
    echo "  -n, --gridpoints           specify number of grid points"
    echo "  --ntsteps                  specify number of time steps (frames)"
    echo "  --tau                      specify time step size in au"
    echo
}

TMPFILE=$(mktemp -u)
#
# parse()
while :; do
    case $1 in
        -h|-\?|--help) 
	    help
	    exit ;;
        -v|--verbose)
            set -xv ;;
	-r|--representation)
	    REPR="$2"
	    TDSEOPTS+="$1 $2 "
	    shift ;;
        -n|--gridpoints|-a|--alpha|-x|--initialposition|-p|--initialmomentum|-t|--initialtime)
	    TDSEOPTS+="$1 $2 "
	    shift ;;
	--)     # no more valid options
	    shift
	    break ;;
	-?*)
	    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2 ;;
	*)      # no more options
	    break ;;
    esac
    shift
done
TDSEOPTS+="--ntsteps 1 --mode exact --tau=$1"
#
tdse $TDSEOPTS | tail -n +2 >$TMPFILE
case $REPR in
    "psisq")
	gnuplot -e "set xrange[-1:1]; set yrange[-0.1:2]; set term
	png size 1600,1200; plot '$TMPFILE' using 1:(\$2*\$2+\$3*\$3) t
'Psi^2' w l lt 1 lc rgb 'red'" ;;
    "wigner"|"sb")
	gnuplot -e "set yrange [-1:1]; set xrange [-1:1]; set zrange [-2:2]; set term png size
	1600,1200; set xlabel 'p'; set ylabel 'x'; set contour both; set
grid; set pm3d border linewidth 0.2; set cbrange [-2:2]; splot '$TMPFILE' nonuniform matrix notitle with pm3d" ;;
	"psi"|"")
	gnuplot -e "set xrange[-1:1]; set yrange[-2:2]; set term
	png size 1600,1200; plot '$TMPFILE' using 1:2 t 'RePsi' w l lt 1 lc rgb 'red', '$TMPFILE'
	using 1:3 t 'ImPsi' w l lt 1 lc rgb 'blue'" ;;
    *)
	printf 'ERROR: Unknown option (stopped)'
	exit 1 ;;
esac
rm $TMPFILE
#seq $NTSTEPS | parallel --joblog=gpar.log -k 'render --ntsteps=1 -n=100 --tau={}*$TAU' | ffmpeg -f image2 -r 10.0 -y -f png_pipe -s:v 800:600 -i pipe: movie.mp4
