#!/bin/bash
#
TMPFILE=$(mktemp -u)
tdse $@ | sed '1,/ #/{/ #/!d}' >$TMPFILE
gnuplot -e "set xrange[-1:1]; set yrange[-2:2]; set term
png size 1600,1200; plot '$TMPFILE' using 1:2 notitle w l, '$TMPFILE' using 1:3 notitle w l"

#docker@e43346200ab5:~/tdse$ seq 100 | parallel --joblog=gpar.log -k 'render --ntsteps=1 -n=100 --tau={}' | ffmeg -f image2 -r 10.0 -y -f png_pipe -s:v 800:600 -i pipe: movie.mp4
