#!/bin/bash
#
TMPFILE=$(mktemp -u)
tdse $@ >$TMPFILE
gnuplot -e "set xrange[-1:1]; set yrange[-2:2]; set term
png size 1600,1200; plot '$TMPFILE' using 1:2 notitle w l, '$TMPFILE' using 1:3 notitle w l"
